language: elixir
dist: bionic
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
before_install:
  - sudo apt install -y automake libtool swig gtk-doc-tools git curl build-essential libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev
  - export PATH="$HOME/.cargo/bin:$PATH"
  - git clone https://github.com/libvips/libvips.git
  - cd libvips
  - ./autogen.sh
  - make
  - sudo make install
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
