language: elixir
dist: xenial
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
addons:
  apt:
    update: true
before_install:
  - sudo apt install -y curl build-essential git libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev automake libtool swig gtk-doc-tools
  - git clone https://github.com/libvips/libvips.git
  - cd libvips
  - ./autogen.sh
  - make
  - sudo make install
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cd ..
