language: elixir
dist: focal
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
addons:
  apt:
    update: true
before_install:
  - sudo apt install -y curl build-essential libvips libvips-dev libvips-tools
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
