language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
before_install:
  - sudo apt install curl build-essential libvips libvips-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
