language: elixir
dist: focal
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
addons:
  apt:
    update: true
before_install:
  - sudo apt update && sudo apt install -y wget curl build-essential llvm clang libclang-dev git libxml2-dev libfftw3-dev libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev libglib2.0-dev liborc-0.4-dev gettext libgtk2.0-dev libtool swig gtk-doc-tools libwebp-dev 
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
  - sudo apt update && sudo apt install -y esl-erlang elixir 
  - git clone https://github.com/libvips/libvips.git
  - cd libvips
  - ./autogen.sh
  - make
  - sudo make install
  - export VIPSHOME=/usr/local
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib
  - export PATH=$PATH:$VIPSHOME/bin
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$VIPSHOME/lib/pkgconfig
  - export MANPATH=$MANPATH:$VIPSHOME/man
  - cd ..