[package]
name = "lvips"
version = "0.1.1"
authors = []
edition = "2024"

[lib]
name = "lvips"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
num_cpus = "1.13.0"
base64 = "0.22.1"

[build-dependencies]
bindgen = "0.71.1"