[package]
name = "lvips"
version = "0.1.1"
authors = []
edition = "2018"

[lib]
name = "lvips"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
num_cpus = "1.13.0"

[build-dependencies]
bindgen = "0.53.1"