[package]
name = "lvips"
version = "0.1.1"
authors = []
edition = "2018"

[lib]
name = "lvips"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
rustler = "0.29.1"
num_cpus = "1.13.0"

[build-dependencies]
bindgen = "0.66.1"