[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "./Dockerfile.aarch64-unknown-linux-gnu"
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get update &&\
    apt-get install -y build-essential libvips-dev libclang-dev elixir && \
    export PATH="/root/.cargo/bin:${PATH}"
  """
]

[target.arm-unknown-linux-gnueabihf]
image = "arm64v8/ubuntu:20.04"
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get update &&\
    apt-get install -y build-essential libvips-dev libclang-dev elixir gcc-arm-linux-gnueabihf
    export PATH="/root/.cargo/bin:${PATH}"
  """
]

# x64 Linux
[target.x86_64-unknown-linux-gnu]
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get install -y libvips-dev
  """
]


[target.x86_64-unknown-linux-musl]
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get install -y libvips-dev
  """
]

# Mac OS
[target.aarch64-apple-darwin]

[target.x86_64-apple-darwin ]
