[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.aarch64-unknown-linux-gnu]

[target.arm-unknown-linux-gnueabihf]

# x64 Linux
[target.x86_64-unknown-linux-gnu]
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get install -y vips-dev
  """
]


[target.x86_64-unknown-linux-musl]
pre-build = [
  """
    export DEBIAN_FRONTEND=noninteractive &&\
    apt-get install -y vips-dev
  """
]

# Mac OS
[target.aarch64-apple-darwin]
pre-build = [
  """
    brew install vips
  """
]

[target.x86_64-apple-darwin ]
pre-build = [
  """
    brew install vips
  """
]
