[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.aarch64-unknown-linux-gnu]
pre-build = ["apt update && apt-get install -y libvips-dev clang libclang-dev libc6-dev-i386"]

[arm-unknown-linux-gnueabihf]
pre-build = ["apt update && apt-get install -y libvips-dev clang libclang-dev libc6-dev-i386"]

[x86_64-unknown-linux-musl]
pre-build = ["apt update && apt-get install -y libvips-dev clang libclang-dev libc6-dev-i386"]